# Publishing manuscripts

## Writing skills for manuscripts
The findings and insights gained in the course of a project have to be communicated to others in an acceptable style and format, which is why scientific manuscript writing is an essential skill. While there is some room for creativity, manuscripts are for communication and, by and large, are not fun. The conventions of the published scientific manuscript have evolved over centuries and gained universal acceptance as a superbly flexible vehicle for describing all the aspects of piece of scientific work in a compact manner. The only sure way to master this writing skill is long hours of practice and  constructive criticism. While that is happening, here are some useful points to consider. 

### Styles of writing used in a manuscript
It is useful to think about a piece of medical or scientific writing in terms of its style characteristics or parameters. There quite a few of these, but the most important would include:

* Journalistic vs dry scientific style. A highly journalistic piece of text has a colloquial or even gossipy style, with interjections of opinion, interesting diversions, human interest points and phrasing chosen for colour and impact; it is easy to read. A dry scientific style has none of these features, rather is has has tightly linked sentences, focusses directly on factual detail and interpretations directly arising from these details. It has high precision but can be hard to read. Most scientific manuscripts are towards the dry end, narrative reviews may flirt with the journalistic style in parts.

* Text density. Highly dense text, particularly used in abstracts, packs in as much as physically possible and shaves off any non-essential words. Comprehension suffers with high density so structure and clarity are crucial. High density text is often but not always seen with a dry scientific style. Scientific manuscripts, aside from abstracts, need to be in the middle of this scale.

* Degree of specialism. How many jargon and technical words to use without definition is important to match to the expected audience. In addition, specialist fields have common conceptual assumptions and accepted types of phrasing and description that must be adhered to, but make it hard for the non-specialist.

* Text complexity. This is usually defined as reflecting the number of long words in the text. As a rule this should be reduced as much as possible in medical/scientific text, but is usually high.

### Starting manuscript development
To decide roughly on the style needed it is important to read articles from the journal where the manuscript is targeted. Most strictly scientific original research articles have a similar style and structure, but outside this category there is a lot of variation. Once the style details are decided, the first step is to define the focus of the article, which for an original research article or systematic review is a specific and tightly defined research question. If data analysis is involved this must be prepared this first as everything else hangs around its interpretation. The text then must be fleshed out, clarified and revised many many times. Ask others to give criticism and, when it is given, accept it with grace and take it seriously. 

### The story
Having a narrative that gives a structure to the central points of your manuscript will help give it clarity and make it more engaging and easy to read, which are major goals. The components of the work is described in an order that brings out that story, but note that this is not usually in a rigidly chronological order of events. Bear in mind that a narrative can be powerful for what it leaves out, as much as what it includes, so omitting trivial detail and relegating extra or negative information in  the  supplementary sections can help.

### Clarity
A manuscript is an exercise in communication, above anything. It is often a record of activity, such as a systematic study, but this cannot be presented in an unfiltered way without compromising clarity and without clarity there will be no comprehension, and without that the manuscript will not make it through peer review. Thus care is needed with grammar, sentences that are short with consistency of descriptors, preference given to concrete words (rather than abstract highfalutin latinate circumlocultions) and without undue overuse of adjectives. In the end, other people must be the arbiters of clarity, so it is wise to have this checked.

### More about clarity
Keep sentences below 3 lines, if single column A4 is used. Use reasonably short paragraphs that contain linked ideas and link paragraphs where possible to keep the flow of the narrative. Try to sound precise and slightly fussy in details. Never be long-winded without very good reason.

### Data
Data presentation is an art itself and should be carefully thought out and discussed with mentors, as it is the core of the manuscript. Again, the key is good communication, so if a table or graph does not help the interpretation (i.e., if it does not bring out the feature of interest) then it should be changed. However, high impact always trumps fancy presentation, so a boring bar graph is often good enough if it makes a simple point. Data tables have the advantage of range and completeness of data presented, but is more accepted in some fields than others. Where complex data does not inform it is often best to move it out of the way to a supplementary data section accessible to those interested.

### Repetition
Repetition (with rephrasing) is a useful writing tool in manuscripts, where a major topic or factor is introduced, then discussed, then a conclusion is reached with it. Nevertheless, repetition must not be overused, so points and arguments that are not central to the enterprise should not be repeated.

### Be mindful of who will review it
Any manuscript will be reviewed by a peer or editor of the journal. Experience here is really a key, so help is needed from someone who has it. Answering reviewer critiques is an art in itself which takes time, much suffering and good anger management. Key points to remember with reviewer replies are to be unfailingly polite, answer questions directly and do not take too much nonsense even if you have to courteously pretend that the reviewer is not a complete clown.

### Publication and manuscript submission
This is a complex process and always takes much longer than you think. Always rigidly adhere to the journal Guide for Authors regarding subject scope, length, structure and formatting. A letter to the editor is required to explain why they should publish your work, and this should be taken seriously. 

### The pat on the back
If your manuscript is accepted for publication, well done. It is no mean feat even for a small paper.

## Manuscript publication and authorships  
This is a brief guide to the issues and etiquette around developing and publishing manuscripts. Preparing a manuscript for publication is always arduous, and involves a long period (usually underestimated) of manuscript development, followed by the journal submission process and peer review, none of which are trivial matters. 

### Authorship
As a rule anyone who contributed to the form and content of a manuscript should be included as an author. Most journals have a guide as to who should and who should not be included in the author list. An author should make a contribution to one or more of the following necessary features of the manuscript: its conceptual development; contribution of important materials needed in the study; the data generation or collection; manuscript writing; figure composition; and critical discussion or editing. Clearly there are grey areas, such as whether technical help is acknowledged, however, contributing only patients to a study, or providing some minor material contribution is not sufficient. On the other hand leaving out a significant contributor to the manuscript is a type of misconduct and potentially serious. It is a good idea to clarify to all authors at an early stage that they will be included. 

Signatures or some other sign of assent of all authors may be required for manuscript submission to a journal, which should be borne in mind if there are any co-authors that are hard to contact.  

### Author list
There are various conventions for authorship order but in biomedical publications the writer of the manuscript and main driver of the project is almost always first author. A newer convention of biomedical publications is that the last author is the senior member of the team and has made crucial, project-enabling contributions. Note that in other fields (e.g., bioinformatics and chemistry) these conventions may be very different. The corresponding author for purposes of manuscript submission is also a significant status and is often the senior author but can be the first author, but must be an author willing to deal with the submission itself. First, senior and corresponding authorships may be multiple, i.e., more than one joint first author or senior author, which is an important convention  when the study is a collaboration across groups.

### Manuscript structure
This varies but almost always includes a front or title page, abstract (150 to 300 words), Introduction (which includes a review of the research area and literature), Materials and Methods, Results (structured description of data) and Discussion section (describing how the data aligns with current literature). The specific details of these must follow the guidelines for the intended journal. 

The text should contain relevant references that support major statements and assertions in the text, and these should be included in a list after the Discussion; then there are the figures and tables and their respective legends that detail the data. Note that some extra data and other information not included in the main text (e.g., negative results or extra analyses) may be put into supplementary figure for most journals. Ideally all the format of text (especially word number of respective sections) and figures should conform to the intended journal, and it saves time and effort if this is done from an early stage. Adhere rigidly to journal requirements for manuscript, figure and table formats and conventions.

### Developing the manuscript
Usually one or two authors take main responsibility of the writing, and it is absolutely essential to get critical input at all stages of development. It should be agreed early how to distribute writing duties and how the manuscript will be distributed for critiques. At the start it is usually best to circulate MS Word documents that can be used to track changes, because structural changes and rearrangements to the text are often needed. Version control is crucial and will drive everyone mad if this is not done properly. A good convention is to adopt one version as the master draft, and to pass this to a co-author for editing and prompt return; during this time no alterations by anyone else should be made. A version number is important in the header and filename to avoid confusion. 

If these points are not adhered to there is a risk of developing parallel incompatible copies. Later, when the structure is clearer but writing amendments and checks still needed, it is better to use an online resource such as Overleaf or Google docs that allow simultaneous editing. When only minor checks are needed at the end, then make sure the drafts are approved by all authors. 

### Writing
Do not be precious about your writing; gracefully accept criticism and edits. Have a story that pulls all your main ideas together will help text flow and clarity. Write clearly and check with others that it is indeed clear and understandable. Minimise complex sentences, aim for only two lines (three at most) per sentence. Link paragraphs. Use clear and informative figures and tables. Use diagrams where possible. Make the conclusions sound strong and important, but note important caveats. 

Remember you know the subject better than most, so do not assume everyone understands your arcane terminology and arguments. Recognise most people do not produce their best writing on first draft, and it needs critiques from others to improve it. Spend as much time as possible going over the drafts repeatedly. Remember the oft-quoted “Easy reading makes hard writing” [Thomas Hood, The Atheneaeum, 1837]; it is always true. Manuscripts that read well and have a compelling argument or story will far more easily get past editors compared to those that are not. You want to be proud of your manuscript when it is print, but there is no short cuts in the time and effort to get it right.

### Dealing with data
Like the writing drafts it is important that the data being used is kept up to date and accessible which may not be simple if it comes from multiple sources. The datasets should be regarded in a sense as part of the manuscript, and care take accordingly. For primary data most journals now require that raw data is publicly accessible in some form, usually in an online repository. 

### Public access to the published manuscript
Many grant-giving bodies mandate early or immediate public access to manuscripts, either via journal website or a public repository. Check the journal instructions for authors how this can be managed and how much this will cost. Bear in mind the copyright may have to be assigned to the publisher.

Manuscript publication is a hard job and you never stop learning. Remember also that writing will always help you refine your understanding and your expertise. For that alone it can be worth the pain, or at least some of the pain.


## How to collaborate on writing manuscripts. 
Publishing a manuscript is a complex process needing a lot of work and much input from collaborators. If this not handled and organised well this hard but manageable task can become a quagmire of floundering conflict and confusion. To avoid this, there are important points to consider. 

Journal publications are the main avenue for communicating scientific evidence and ideas, and they demonstrate the authors’ contributions to the scientific corpus. That is why publication metrics are used as productivity indicators in grants, awards and job interviews, so authorship on paper is a big issue. Collaboration is essential for manuscripts to see the light of day (evidenced by the extreme rarity of single author research publications) so this must be managed well.

### First stage of manuscript development: shaping the idea and getting the data
When starting out with an idea for a manuscript, working with collaborators and colleagues is useful to review and discuss the literature, as well as assess and extend any data. Manuscript co-authors become evident from this process, as it is crucial to properly acknowledge contributions to the paper. It is then necessary to decide who should be first (or joint first) authors and senior authors.

### Authorship status
First authors are the main drivers of the project and manuscript writing, while last authors are those with senior status overseeing the project. Clarity about each author status and contribution is important. Sometimes at a later stage the contribution one author may increase to the point they can be justified to be first authors, but it is hard to go back on undertakings to the original first author, so this must be handled sensitively; joint first (or joint senior) authorship can be a good solution. 

### Second stage of manuscript development: presenting the work and preparing figures
Data analyses need to be assembled in figures and text to present at oral and poster presentations. These are great for practicing figure construction and writing, to test out the narrative structure and to get critical feedback. Indeed, the best feedback may well be from collaborators who can now see the project taking form, so a copy of any poster or slides should be sent to all of them beforehand with enough time to provide comment. It is also a courtesy, as it demonstrates they are involved and that their input is appreciated. Bear in mind that authorship lists on conference presentations will create expectations for author inclusions and author list order in the related manuscript.

### Drafting a manuscript 
It is usual that text and figures are worked on by one or two authors with critical reading by other authors. Version control is crucial, as without it there is a confusion of parallel draft alterations, plus the nasty risk of contributors amending out-of-date drafts, which will deeply annoy them. For early drafts, e-mailing (MS Word) copies of drafts for co-authors to make tracked changes is good, but there are also good online options such Google Docs or Overleaf.com that allow simultaneous editing. It is best not to perform major surgery on a draft while others are working on it, so this should be managed carefully. Among around manuscript development issues, a thorny one can be deciding which points should be put in the Introduction and which in the Discussion section.

### Authorship etiquette in manuscript writing
It should go without saying that the main manuscript author should treat other co-authors with proper consideration. This includes clarity over their roles, and treating their edits and amendments seriously. Requests for input from other authors should give them time to respond before deadlines; an unexpected request sent late on Friday for a Monday morning deadline is not respectful. It is also important to actively acknowledge the contributions of particular authors that have put in effort.

It is nearly always difficult for inexperienced writers to accept criticism without being defensive. After working long and hard the new writer gets emotionally attached to their creation. Experienced writers know a near-Buddhist lack of attachment is best, as you may need to sacrifice your favourites for the greater good. There is also the Dunning-Kruger Effect which, paraphrased for the context, is that inexperienced writers have yet to learn enough about writing to understand just how awful their scientific prose really is. A trusted mentor, or a senior colleague whose irate opinions cannot be ignored are usually the only fix for this. As a major point of etiquette, do not plagiarise others. It is always unacceptable, easily detectable and, hence, always embarrassing. However, it may be reasonable take a short piece of text by a good writer to recast later in your own words. 

With manuscript done, always get permission from all authors before journal submission; failing to do this really is a cardinal sin. Usually a first or last author is designated ‘Corresponding Author’ and performs journal contact tasks; note in some circles, being corresponding author carries extra status.

### Research ethics and collaborators
This is a huge subject, summarised thus: be honest, be open, be scrupulous and always do things in good faith. Do not cut corners on this. Make sure data and data analysis is correct and get it checked by others. If you suspect the ethics of a co-author or data supplied by them, seek mentor advice before the problem snowballs. If something is wrong do not delay to deal with it. Make certain of ethics committee approval for the work – ethics approval numbers will be needed for journal submission.

### Third stage of manuscript preparation: finalising the manuscript
Once structure, narrative and data is done at last, finalising it all in a publishable draft can be surprisingly long-winded. Almost everyone (even those most experienced) underestimate this, often hugely. This is due to the need to inspect the work from every angle, and it is common to find major data issues only with writing underway, e.g., a vital control group not included, or a minor section that has become major starts to wilt under the increased scrutiny. Get co-authors to help with this process, as extra brainpower is needed to spot problems before peer-reviewers do. 

Do not submit a manuscript without appropriate input from all others thinking that the journal reviewer will provide the appropriate suggestions; that approach never ends well. Read, read and read again the manuscript and do not be afraid to make changes even in the underlying principle to make the writing clear and concise. Be brave and delete words or paragraphs that do not clearly add value. 

### Fourth stage of manuscript preparation: the fiddly bits at the end
So many fine details and minor features (including formatting for journals) need to be finalised for journal submission that it inevitably takes far more time than seems reasonable. It is not hard but here, alas, the first author is usually on his or her own.

### The peer review process
This is not an easy process to navigate, so co-author help is needed at all stages, and it is essential get their approval before a response to peer review is submitted. Take peer review criticism well and courteously. Provide any further data that is requested or provide good reasons why not, for example, if it would give uninterpretable results or is outside the manuscript scope. This is a delicate craft requiring experience and good advice. It is generally understood that a journal editor will accept the manuscript if the authors properly respond to the points raised by the reviewers. A second review by the same reviewers is needed to confirm this, and it is a convention to help preserve everyone’s sanity that the second (i.e., last) review will not raise substantive issues the first did not, as it allows no possibility for response. This is not always true of the highest journals, however, who do as they see fit, because they can.

### Money
Do not forget most journals charge publication fees, so make sure the appropriate funds are secured before submission.


##  Producing the first draft of a research manuscript 
Here we go through the steps of developing a piece of research work for publication in a reputable journal, and some time tested strategies. 

### Starting on the blank page
Before the first text keys are tapped, the findings of the data analysis should be very carefully examined, and how the proposed paper might fits with other published work in the area thoughtfully considered. Note the data serves the paper and not the other way round - some data and analysis may, in the end, be left out. The main points, arguments and conclusions can then be summarised in bullet form. It is a useful thinking aid to place these points in order priority and importance, and evaluated as to which must be in the paper and which are less essential. 

### Journal choice and information on format
It saves time later if the formatting of the manuscript is right from an early stage, so it is good to choose a target journal, then consult and adhere to their “Instructions for Authors”. Then it is good to start to write out formatted section headings, and add the above dot points where appropriate. Thus, a document is produced with a Front page (title, names, affiliations), Introduction or Background, Patients and Methods, Results, Discussion, References, all ready to be fleshed out. The document should from the beginning look like a proper and neatly crafted manuscript. The authors will then see a real paper emerging in front of them, giving the enterprise some feeling of momentum gained.

### Assembling the data
As soon as possible key data should be assembled in a presentable and finalised (or near final) form. The conclusions that form the basis of the paper can then be written in a short, direct way with a minimum of hedging, fudging or caveats. Everything will then rest on how well the data will buttress those conclusions. It is often useful to draught out (on a whiteboard perhaps) a layout of the figures, tables and diagrams to work out the best sequence they should appear in. This process constructs the manuscript narrative, and it needs to be discussed in detail with the other main authors and mentors. Note that having a rich array of data and methodologies (even if some is later relegated to the Supplementary sections to save space) helps to impress editors and inspire confidence in the work.

At this stage it should become evident if there are any significant data or information missing, but if all the essential data is in place then text development can proceed. If it is not, there is a risk that new data arrives that radically changes the manuscript. 

### Writing up Results and Figures
After the general outline has been envisaged, it is usually best to put together a rough version of the Results section based on the figures drafted above. A logical sequence of Results section subheadings, fleshed out with concise descriptive text is needed. It starts with plain but scene-setting data and data that confirms the work of others. Good figure/table/diagram legends should be written at this point, using the journal conventions.

### Introducing everything
The paper scope should be evident at this point, so work on the Introduction should start; it may take time to develop since consulting the literature often throws up unexpected challenges. This section starts with general statements about the field or clinical problem, noting particular and peculiar features (including its importance of the field and the challenges it presents) which expand into a solid but short review of the field that highlights key knowledge and areas of ignorance. It will display a firm grasp of the subject and make clear what knowledge gaps the manuscript will fill, and lead the reader logically to the work presented in the manuscript. The Introduction should mention the research approach employed and why it was chosen.

### Methodical with Methods
Writing the Methods section is always useful as it involves a lot of formulaic sections (e.g., details of ethics approval, statistical approaches) that are easy to write but take time. There must be enough method detail presented to support the technical credibility of the paper. 

### Discussion among friends
The next part to tackle is the Discussion section which should be developed slowly with many revisions, as this helps the logical development of the paper. The section should begin with a brief summary of the most important Results, then a section that carefully considers how the results of the study do (or do not) support the project aims and hypotheses. This should merge into discussion of the major literature on the subject and how the study fits with this. The Discussion should clarify the limitations of the study, and what future work it might lead to. The section should close with a statement of conclusions of the study that does not just restate the Results yet again, but brings out the key messages that emerge from the Discussion.

### The next steps: Abstract and referencing
The work completed up to this point should enable the construction of the Abstract. This requires a whole set of writing skills in itself as there is nothing quite like it in style, but its structure and content has to accurately reflect the manuscript Introduction, Methods, Results and Discussion substance, hence why it is best left until these sections are at least drafted. The Abstract begins with a terse description of the problem and state of the field and ends with the conclusions. In between, there is the narrative sequence of arguments and information. Reducing abstract length and stripping it to essentials is needed and must be ruthless as word limits in journals are rigid. If it is too long, leave it aside for a while in order to view later with fresh eyes.

There should now also be proper referencing that supports points raised in the text. This requires obsessive and careful literature consultation. A neat way to evade immediate tangles with reference manager software at this stage is to insert citations in the text as simple PubMed ID numbers. These can easily and rapidly replaced with the proper format in later drafts.

### End of the first draft
The development of the manuscript to this point probably involved collaboration between authors, but if not then it must begin here. A choice of document sharing strategy must be made – will the text be circulated as MS Word and PowerPoint documents, or online shared documents such as GoogleDocs or Overleaf? Whatever is decided, version control is crucial to avoid time-consuming blunders made like editing old or out of date drafts. Thus, it is best to be clear which file is the ‘master’ or definitive version, with only one person editing it so confusion is avoided. However, online document tools (such as GoogleDocs) can allow simultaneous editing by more than one author which can get round this problem. Whichever system is used, tracking document changes is very helpful as they make amendments visible for all the authors to consider. 

### Onwards
With completion of a first draft much has been achieved but much remains to be done. This will take time and it is important not to underestimate this. This is scientific writing, and while it needs to be succinct and pointed it should also read well to maximise the chance the reviewers and editors will accept it for publication. The draft needs persistence to ensure the narrative and messages are clear and eradicate unnecessary adjectives, adverbs or notions that do not contribute to the main themes of the paper.

* “Hard writing makes easy reading, while easy writing makes hard reading” 
(Attr. to Thomas Hood)*

## Manuscript citations 
A prominent feature of a scientific manuscript is the care with which citations have been added to the text. Any assertion made in the text is linked to a source of evidence (hopefully solid evidence) that supports that assertion. In any manuscript intended for publication this must be done well and thoroughly, so here we discuss the ins and outs of how to ensure this is achieved.

### What is a citation?
This is a reference to a previously published work that is commonly accessible. In the pre-internet age of distant memory such ‘access’ often meant long waits for printed copies (or photocopies) of the work to be arrive, but access blocks due to internet paywalls are the main barriers now. Most citations refer to journal articles and (less commonly) to book chapters and conference proceedings. The detail of a reference itself is usually quite long, so it is placed at the end of the manuscript with a link at the text location where it is invoked. In this way a reader seeing a contentious claim in the text should be able to locate the supporting evidence with a minimum of fuss.

The work referenced may be a primary publication, i.e., a full original research article, an essay, a literature review or, on occasion, a published abstract. Peer-reviewed articles from a respected source are always preferred but a citation may from necessity refer to a grey literature item, such as non-peer reviewed internal reports and policy papers.

### Where are citations needed?
Any assertion of fact in a manuscript needs to be referenced to a source that supports the assertion. Citations need to be inserted either next to the assertion in the text or at the end of the sentence; unreferenced assertions are frowned upon unless the assertion is accepted as common knowledge. Where a good reference cannot be found to back a claim, the claim should either be excised or appear with a remark about its lack of substantiation.

Where a very general claim is being made, or the claim involves a lot of detailed papers, then citing a literature reviews provide a good shortcut and (an important consideration) it helps keep down the length of the manuscript reference list. However, citations of literature reviews should not be over-used, and the reviews themselves should be checked that they are appropriate.

### What form does a citation take?
Usually there is an abbreviated reference, often a reference number, which can be looked up in a list of references at the end of the manuscript. Within the text the reference number can be a superscript or in brackets; alternatively, it may be in the form of first author name plus “et al.” (if there is more than one author) plus a publication year all placed in brackets, but this appears to be becoming less common. Note “et al.” is universally employed to mean ‘and others’, but it is a Latin abbreviation (et alii/aliae depending on gender) so italics and a full stop are the convention. 

The in-text format and the references list format used for the manuscript depends on the preferences of the intended journal, which can vary widely, so the journal “Instructions to Authors” needs consulting.

### Checking references
It is important not to use an inappropriate reference, so cited papers need checking with care, i.e., the referenced paper (or at least its abstract) should be read. It can be dangerous to rely on a paper title alone to indicate its content, although for very obscure or old papers there may be little alternative. The details citation itself must also be accurate, which is not difficult to ensure with digital resources.

### How to find sources to cite
It is useful for citations to be inserted into the text while the text is written, because if an assertion of fact is made which later becomes central to the manuscript narrative then it will cause embarrassing problems later if the source cannot be found. Virtually all journal publications should be accessible at the NBCI PubMed resource1 which accesses the Medline bibliographic database, and careful and wide-ranging searches should be undertaken. Note that the unique Pubmed ID number (PMID) for a publications is a fairly foolproof way to locate the reference later on unless the reference is outside the biomedical field. Outside of the main biomedical literature there are also commercial databases like Web of Science, Scopus and Proquest which have their own conventions.  

### Deciding which publications to cite
There are no certain rules on deciding appropriateness of a citation, but there are some expectations and rules of thumb. A general statements is often best supported published reviews, while a specific statement is best supported by a citation (or two) of research papers that directly provide support, preferably declared in their abstract. To avoid excessive citations some journals encourage using published review citations more liberally, even though this is often not ideal. An obscure or doubtful publication should not be chosen over a more reputable one, and here consulting published reviews to identify the seminal papers is useful. Withdrawn publications should not be cited. Where no citation can be identified this may indicate a knowledge gap that could be commented on.

### Inserting citations into text
Putting references into text can be a fiddle since the software that does it tends to be clunky. Until recently the most common types of reference manager software were proprietary programs such as Reference Manager (discontinued 2015; Thompson Reuters), SciRef (now version 1.5; Scientific Programs) and EndNote (now version X9; Clarivate Analytics) that search for and download PubMed data then link it directly to text in MS Word documents. There are now alternative managers available, and some free are free. such as Zotero (New Media). LaTex publishers (usually free or freemium model) such as Overleaf.com enable insertion and formatting of in-text and end-text references using a coding approach. These are increasingly useful as they can take in records and format that can be obtained with minimal hassle from PubMed. 

### Formatting of reference lists
Reference formatting has always been a nuisance since there are so many ways that journals can cite articles. For any manuscripts the instructions to authors should be consulted and followed carefully. Templates for particular journals are often available in reference manager software, however these are occasionally wrong so should be checked that their output looks like what appears in the target journal. A common type of reference list is the so-called Harvard System but, annoyingly, no definitive standard for this system exists; for journals a typical format is Author list (in comma separated surname - first name – initials order), year, article title, journal title, volume, issue, page number and DOI.  

Citation conventions can be quickly grasped and become second nature when writing documents, so becomes hard to write a document without at least one reference.

* www.ncbi.nlm.nih.gov/pubmed


## Writing manuscripts abstracts – one of the hardest writing skills

All manuscripts need an abstract or summary, usually 300 words long, and after publication it is the abstract that an interested reader will first engage with the work. Journals care a lot about abstracts, not least because they care about citations, and a badly written abstract will repel potential readers who might otherwise cite the work. Authors themselves similarly care a great deal about having a well written abstract that shows their work in a good light, so abstract writing is an important skill to develop.  

The biggest problem faced by an abstract writer is usually that it is hard to shoehorn a lot of information into 300 words and keep it coherent and readable. With this in mind, below are some approaches to write manuscript abstracts as well as conference abstracts, which are only a little different.

### Starting out
An abstract is in effect a fully self-contained document, so can be read without reference to anything else. A special effort should be made to make sure that the pre-amble and the conclusions at the end are as clear and simple as possible, as these are often the parts that readers go to first and will remember and which will frame the other more technical parts. The introductions and conclusions of an abstract should use concrete and precise statements, and not include vague language or include wildly overoptimistic claims. 

### Obey the abstract constraints
The first task is to identify the abstract word or character limit and to stick with it. If it is to be submitted online it is often the case that the limit will be enforced automatically by the submission portal. If there are other constraints, note them. One to look out for is whether the structure is mandated, e.g., it prescribes a labelled Introduction, Methods, Results and Conclusion sections. Do what is asked, or risk rejection or, at the very least, instructions to rewrite.  

### Conference abstracts
Conference abstracts differ from those in manuscripts in that they are written from scratch well before much of the project presentation is prepared, while manuscript or report abstracts summarise and are part of a relatively mature document. The conference abstract is written to appeal to the committees and attendees of a conference that lies some time in the future, sometimes after more work will be completed. To avoid regret it is crucial that any result reported in the abstract is already obtained, done and dusted at the time of submission, and not merely anticipated to come in future, tempting though that may often be. If possible include some illuminating summary statistics in the abstract.

The following is one fairly common approach to constructing a summary abstract which can work when the abstract length is very constrained.

### Stage 1: assembling the pieces.
This is done more or less backwards, with the conclusion written first. This may be an expanded and more precise version of the manuscript or presentation title. Bearing that in mind, the next thing is to write out in rough dot point form what study results need to be included to buttress that conclusion. Do not include anything that does not contribute to the impact or which cannot be explained well in concise terms. Next, list the methods and clinical information needed for the results text to make sense, although specific method details can usually be abbreviated as in, for example, “a systematic review was performed”. A preamble that places the study in its context and makes it clear why the study was done (and why it is important) can then be added at the top of the abstract. Finally, at the end of the conclusion a short sentence might be added explaining briefly what it the conclusions mean or imply in the clinic.

It does not matter if the abstract is over-size at this stage, as it is important to make sure important material is included. Then the abstract will need to undergo a series gradual (but often painful) reductions. 

### The first amputations
The abstract first is examined carefully for significant omissions and for any text that could, on mature reflection, be left out. The abstract length should be compared to its required length to get a good idea of the level of discomfort ahead. Any loose phrasing such as “in general it was observed” or “there is a great deal of evidence that” can be slashed. The introduction can also be truncated if it is clear that the audience is an informed one. Then it is usually best to leave the whole thing aside for a while, a few hours at least, but a couple of days if possible.

### Stage 2 – the cycle of text reduction
When returning to the abstract it will be clear that there are sections that can be excised or revised to shorten.  It is often best (where possible) to go through a few rounds of cutting followed by a rest of a day or so before returning to the job. However, as the options narrow it can be necessary to recast long sentences to carefully shave off a few words here, an adjective or stray comment there. As the density increases it really helps to have a strong grasp of the language, so if English is not your native language then get some help. Cycle by cycle the abstract size will reduce as originally prized turns of phrase or nice but bulky explanations are sadly jettisoned.

### Stage 3 – the unsuspected cruelty of other people
When you can do no more, but still the length is excessive then it is time to use the eyes of an objective colleague or mentor. You may be emotionally attached to your text, but they are not. They come to it afresh and will not hesitate to suggest cuts or restructures.  

### Stage 4 – discussing with the co-authors.
When the abstract is a reasonable length and in a good state it should be shown, ideally with the rest of the manuscript, to the other co-authors for their feedback on the content. If they are engaged they will suggest new perspectives and highlight issues, but hopefully not too much if deadlines are short. Indeed, it is often useful to be clear about a deadline for responses in the email used to circulate the abstract text to avoid hold-ups.


## Writing a manuscript introduction
A research manuscript Abstract summarises and advertises the study, its Results section, (with its figures and tables) catalogue what the study found, the Methods section how it was found and the Discussion and Conclusions explain what it all means. The Introduction section connects all these, and provides an entry point for the critical reader looking for details of the study itself. It provides a brief summary of current knowledge as well as knowledge gaps in the field, and gently leads the reader towards the questions the manuscript is addressing. It may also give a few pointers to the research approach used. Here are some general pointers on how to construct a good Introduction section.

### Starting out – writing and thinking
When starting to write the Introduction some outcome data and method details should to be in place to help guide the writing. Nevertheless, it is a good idea to write an Introduction draft as soon as possible as this both helps give a concrete shape to the emerging manuscript and practices the arguments and narrative that will be used. 

### The scope of the manuscript,
It is important to be clear about the scope of the manuscript and how general or focussed its subject when writing the Introduction. There is little point in writing much on subjects that the manuscript does not address, as this will only distract and irritate the reader. Thus, for example, introducing a study on an HIV infection prevention strategy will not require an extended essay on AIDS (unless the audience is somehow unaware of AIDS) but rather a brief summary of the relevant features of HIV infections with an overview of current prevention strategies. 

### Style
The Introduction provides an opportunity to write plainly as it does not have to be as dense as the Abstract nor as dry and detail-focussed as the Results and Methods. However, every sentence should justify the space it takes up, should be short and should be carefully linked to other sentences to make the text flow well. Most journals have word length limits (which should be checked) and readers have their limits too. A short, clear and informative Introduction that is stimulating and easy to read is the general aim, which will not only encourage the reader to continue through the manuscript but also persuade even difficult editors that the manuscript should be taken seriously. Achieving all this takes time and many revisions with input and polish from other authors.

### Models
If there are other papers close in subject matter it is always useful to see how they have written their Introductions. These should be carefully examined to identify features that would be a model to emulate though, of course, not emulated too closely. Those papers should in any case be read to provide clarity about the current state of the field, and to help crafting the manuscript to bring out its novel and important aspects, emphases that should be prominent in the Introduction.

### Preambling
The very first part of the Introduction should be a preamble sentence or two that raises the general topic that the manuscript will address. This is needed so that the reader can immediately engage with the subject and judge its relevance to them. The necessary brevity of the preamble means it can do little more than state why a disease or condition urgently requires our concern, and what has previously been done to address it. This sets the stage for the next part.  

### Overview or background of the subject
This part is a mini-review of the subject area, with appropriate references. This outlines what is known of the pathobiology of the condition and its important clinical features. This section forms a substantial part of the Introduction, more than half, and should be useful to any readers interested in the field rather than in your work.  Indeed, if there are no narrative reviews on a subject then reading the Introduction sections of papers in the field can be the next best thing. However, this mini-review should not contain excessive detail beyond that needed to comprehend the study and its outcomes. Hopefully, the reader will become better informed, and confident that the subject is important and that authors have a firm grasp of it. 

### Leading into the rest of the manuscript: why was the work done?
Next to include are the important questions that remain in the field, and specifically what questions the study addressed. That research question, decided when the study was originally designed, is usually summarised succinctly in this part, although in some cases it may be better to put in the preamble. There should be a note regarding why the particular approaches or methods used were employed; this can be an opportunity to head off reviewer arguments that another approach would be better. The research hypotheses may be stated here, unless the manuscript is exploratory rather than hypothesis-driven, in which case the research strategy needs to be outlined. 

### The ending
Lastly, the last few lines of the Introduction should note the intended outcomes of the study. Alternatively, the main actual outcomes of the study could be mentioned. Choosing which alternative will depend on the journal targeted, which should be examined to find its preferences.

### Introduction versus Discussion
Included in the Introduction will be a lot of material on the background of the study but this may end up making the Introduction too large. One solution is to move some of it to the Discussion section, where there is more space and it can enlighten debate around the study findings. It can indeed be hard to decide what to put in the Introduction and what in the Discussion and neither option may be perfect. Whichever is decided, the priority is that the Introduction is short, well structured and does not ramble on about peripheral subjects. Some text may have to be moved or removed to achieve that, and some imperfections are inevitable.

## Writing the Discussion section of a manuscript.
After the scene has been set in the manuscript Introduction, the data that supports the manuscript is detailed in the Methods, Results and the figures. The Discussion section is last on the list to compose. It is often viewed as the dull anticlimax at the end, but in fact it is a very important part and has its own peculiar requirements. Here we discuss writing it.

It is true that the Discussion section is probably the least consulted part of the manuscript because to fully appreciate it requires a deep knowledge of the subject that not all readers have. An important exception will be peer reviewers, who will read it very carefully. Ideally they will find the strengths of the study are made clear and any apparent problems with the data interpretation addressed in a scholarly way. 

Thus, even if it is a little arcane the Discussion must be good. There are manuscripts where the data more or less speaks for itself, but even there the Discussion must pass muster. It is in the Discussion section that the outcomes of the manuscript are linked clearly to the current state of knowledge about the phenomenon of interest. There also the data (and its interpretation) should be subjected to withering critique, yet shown to remain standing if perhaps quivering a little. The Discussion also includes writing about other relevant studies of the subject; here, there is sometimes an opportunity to have a little fun (but only a little) by critically evaluating the work of other groups.

### The most common mistake
A frequent flaw in Discussion sections is to simply recapitulate the Results. That obviously does not add value, so if the Discussion section reads like a re-run of the Results section then it is bad, as the reviewers will usually indicate. A brief summarising of the main Results is usually needed, but that is all. A Discussion section differs quite fundamentally from a Results section because it is discusses (the clue is in the name) while conversely, the Results section should contain relatively little discussion of outcomes, enough only to link the parts of the Results section fluidly.
 
### The first part of a Discussion section
Thus, for the Discussion section to draw together the themes raised in the manuscript, and link it to current state of knowledge, a brief recapitulation of the main study results is needed. This should be concise, fluent and limited to the points to be discussed. This summarization usually occupies the first paragraph or two. Alternatively it may be mixed with other elements and dispersed through the Discussion section, a style used when results naturally fall into distinct parts that need their own discussion.

### After summarizing the Results talk about what they mean and how good or bad they are.
This is mainly what a Discussion section is for. The Results should be discussed in terms of their reliability, strengths and weaknesses and contrasted with other published work. This mulling over of the Results should raise key features and conclusions of the work, the most important of which will also appear in the abstract. 

### The Discussion section should contain some support for a thesis
A thesis, or proposition, is usually the focus of a paper, unless the paper is purely descriptive in nature. The Discussion will put forward that thesis and examine how it is supported by the study results (and other peoples studies), rather than simply displaying learning and erudition or showcasing a lot of all the hard work. The Discussion is where the ideas underlying the study will emerge based on what survives criticism. The tone should be disinterested, and display a real sense of curiosity and interest in what the outcomes might mean.
	
### Explain what should be done to fix particular weaknesses in the paper
It is important not just to expose the weaknesses of the paper but to try to fix them as much as it can be done. Where there is a remedy for a particular weakness (e.g., do a bigger study) it must be clear that this is beyond the scope of the manuscript. If you mention a simple or easy fix for a perceived flaw in the manuscript you will probably be asked to fix it before publication so careful thought is needed round this issue. If the fix is not so simple, it should be explained why.

### Linking the work to the wider literature
How does the data relate to what others have seen? Has it reproduced the observations of others? All the relevant literature must be cited, unless it is very extensive in which case cite the main studies and reviews.

### The Conclusion
In some journals the conclusion is a separate section, if not it will be the last paragraph or two of the Discussion. It should briefly mention again the main problem or question that the study set out to address, the main features of the Results and what was concluded from these in the light of the current body of knowledge. After that there is only a wrapping up sentence, perhaps a peroration or high point that inspires enthusiasm for the work, summarizing what it means and what it points to for future studies.  

## Performing a journal peer review

It is a great idea to perform journal peer reviews as it is an excellent way to hone skills of criticism and argument, get a better grip on the subject and gain some recognition with the journal. Lack of previous experience should not deter, but there are some considerations before accepting the responsibility. 

The first consideration time and timeliness – most reviews must be done within in a 10 or 14 day period, though journals may allow more time if asked. The work burden is significant, and can take several hours, so it is essential that it is possible to do it in the time available.  It is not fair to the authors if the report is very late and it is best to be frank about this with the editor.  It is never a good idea to accept to do too many peer reviews proposal exactly for this reason. The second consideration is expertise in the subject are – do you have enough to do the review? The third consideration is support – is there somebody experienced who can advise or help on the review? 

### What is peer review for?

Articles for publication need to ensure the quality of the publication. It is not expected to be, nor can it be, a perfect process. It can only be considered an important filter of quality. It is not the last word on the quality of the publication although unfortunately careers can be affected by the outcome of a manuscript review, especially in higher impact journals. Peer review can be subverted and gamed, but is still recognized as essential.

### Who does peer reviews?

Anyone who has a publication record in the area may be chased to do a peer review. Reputation for expertise counts, which can mean that senior scientists and clinicians are asked a lot. Thus a senior clinician who cannot perform the review will often nominate a junior colleague or student. This is where most people get their first chance to review and it is an expression of confidence that the junior person can do it. Note also that usually peer review is anonymous to the manuscript writers.

### How is a peer review used by a journal?

Journal editors want to know if the manuscript is worth publishing, whether it needs significant or minor revision, or whether should be rejected. The two key points needed to accept a manuscript (with or without revision) for an original research work is that the subject comes within the scope of the journal (a decision more for the editor) and that the data supports the conclusions. Other important considerations include how well the manuscript is written and that the data look plausible, if it is capable of replication (in principle) by others, and is free of any fraud or other dishonesty.

### Can opinions about the manuscript be direct or is deference needed?

A peer review should make direct statements about the details and execution of the study and the manuscript, but it is essential to be polite and not aggressively negative or mocking. Reviews should be supportive to the authors as far as possible and phrased with kindness, consideration and, if merited, gentle diplomacy. Advice should be given where it is clearly needed. 

### What happens if evidence and data are incomplete in the manuscript?

Be circumspect about asking for more data, where it would be hard for the authors to comply. However, if the evidence as presented fails to support the conclusions then it is a central point that must be raised. If the authors cannot comply or amended by the authors the paper must be recommended to be rejected.  The authors will have a right of reply and an opportunity to revise the writing and add data if they wish. Note that if there is some data that might improve the manuscript but is not essential, the convention is to ask the authors if they can add it, rather than demanding that they must supply it.

### What is the process of undertaking the review?

Best is to read the manuscript thoroughly, abstract first then tables and figures, the key parts of the paper upon which it will stand or fall. Scrutiny of data quality and statistical analysis is crucial and expertise is needed. Then the rest of the paper should be assessed. Notes should be made on every important point, and any perceived flaws. Other relevant literature should be checked (briefly) so manuscript consistencies and differences with other published work noted. Then the review report can be drafted.

### What about errors in the text?

Serious problems in the manuscript reasoning should be noted. Problems with language or typos should be mentioned in the report without necessarily listing every example. Comment in the report on clarity and the standard of English, but a manuscript should not be rejected solely because the language needs work unless it is truly impenetrable.

### What sort of reports need to be submitted?

There are typically three parts to the report. There are accessory questions (usually drop-down menus) such as whether the statistical analysis or the conclusions are sound. Then there is a main detailed report for the authors (and editors) to read. Lastly is a direct report to the editors, which the authors do not see. There will also be options to choose recommendation of manuscript acceptance, revision or rejection.

### How to write the report?

For the main report to the authors, there are no hard rules and some people just state very few bald points. However one good approach is to start by briefly describing in one sentence what the paper is about (some reviewers write whole sections on this), then say one or two positive things about it, and state if the study is sound or not. Indicate how clearly the paper is written, how well the conclusions are supported and how important the study outcome is. Then, usually, comes the “However…” statement – the most important concerns about the paper. Then list as dot points each major detail that the authors must address to get the paper acceptable to you, lasts minor points and typos. If there are no major points then the paper presumably can be accepted with minor revision, or is so hopeless it must be rejected. Note that the latter are quick to review. Review reports can be long but it is best under a page.

Note there may be specific things to raise, such as the declaration of ethical approval, study preregistration and others, but that depends on the type of study the manuscript describes.

The last task is the statement to the editor. This is not seen by the authors is best brutally frank and open on the merits or demerits of the paper and what it would take for the paper to be acceptable. This should be brief (the main points are made in the other report), just a few lines.

### What happens next?

If the editor decides that the manuscript has merit the authors will be invited to submit a revised version. You will be asked to review this. Your sole concern should be whether your concerns in the first report has been properly addressed by the authors to your satisfaction. It is conventionally regarded (aside from the very high impact journals) as unreasonable to bring up fresh objections that were not in the first report, unless the author’s response brings up a new bombshell. If the revised manuscript is alright then simply note any minor points remaining to be addressed, and leave the rest to the editor. 

## Responding effectively to a manuscript peer review

Once a painstakingly crafted manuscript has finally been sent off to a journal editor a load may seem lifted from the shoulders of the corresponding author but, of course, the relief is temporary. Perhaps a month or later it will return with a journal response, including detailed and painful critiques from peer reviewers. Here we discuss some ways to cope with this stage.

### Opening the letter

Other than for short subject review articles it is almost unheard of to get full acceptance with the first review, so read the editorial letter with this in mind. Editors filter manuscripts before sending to peer review and will return a manuscript without review if it is outside the scope of the journal or of insufficient interest to the editor. This type of rejection arrives rapidly (perhaps a couple of weeks), since peer review is not done, and the editor may suggest the manuscript be sent to a sister journal for consideration. However, if the manuscript was peer reviewed, then the editor will apologetically inform the authors that the journal will not accept the manuscript, then will go on to indicate whether the journal will consider an amended manuscript. If they will, then it can be considered a conditional acceptance, so is good news. If not then it is bad news, as it is a rejection and (after taking appropriate account of the rejection criticism) the manuscript must be sent elsewhere. 

### Rejecting a rejection

If authors feel that a rejection is unfair due to (say) a badly misinformed peer review, the authors may consider a letter of appeal to the editor. Such a letter must be short, and demonstrate the flimsiness of the reviewers’ main criticisms, while indicating how the manuscript can be easily improved to counter such criticism. All arguments should be calmly stated (not angry), logical and concise. Aspects to raise include strong supportive evidence from the literature, logical inconsistencies between reviewers on the disputed flaw and whether the journal previously published work with similar apparent issues. Such appeals do not stand usually a good chance of success (it is hard to generalise) but can be worthwhile.

### General considerations and the editor perspective

Editors are looking for manuscripts that are going to boost the reputation and impact factor of the journal, i.e., papers in the journal are well cited. Manuscripts that are clear and compelling to the editor (and so the journal audience) will be treated well, so they must be well crafted. Correspondence with an editor also needs to respectful and clear. Note that disagreements between reviewers may oblige the editor to go to an additional reviewer, which can take time. 

### The peer reviews and the types of criticisms (minor, textual, actionable and arguable)

Identify reviewer points that are very minor (e.g., a typo) or that can be dealt with by altering the text and deal these immediately. Where a reviewer is very negative about a point it should be addressed in the letter along with corresponding amendments to the text. Where a reviewer objection is raised that requires more work, e.g., undertaking further analysis or adding another study then (if that is feasible and reasonable) it should be done without further ado. Do not simply state that that the work will be done in future studies, especially if it looks easy to do; this is a red rag to an editor. 

When a reviewer demands something that is arguable or wrong, craft a direct response to this with the help of experienced mentors to try and get the editor onto your side. It can be a good strategy to demonstrate the inanity of a demand to do some pointless work, only then to partly concede (for purposes of goodwill) to add a little extra material. 

### Framing arguments 

All discussion of reviewer points must be good natured and scholarly, with an assumption that the reviewer is acting in good faith. Over-politeness and lengthy anguished arguments are of little use where a straight and simple response can be made, as editors are busy. If the reviewer (or editor) is wrong on a point then say so but be prepared to back up the argument with literature references or other argument. The central substance of a reviewer objection should be clearly addressed, and if the objection has merit then concede it and try to repair the manuscript accordingly. 

If reviewer demands go well beyond the scope of the work, say so and explain why. If the reviewer demands the manuscript work must answer a question it was never intended to address, say so and explain why. If a reviewer demands work that would give open ended answers (i.e., would not provide anything conclusive) say so and explain why. If the reviewers demand is simply unreasonable (e.g., too much difficult work) then say so but be prepared to submit the paper elsewhere if the editor does not agree.  Lastly, on rare occasions a reviewer critique is a firehose of strange questions and objections: this may indicate lack of good faith after all. A response may need input from an experienced hand for a letter to the editor raising a possible reviewer conflict of interest. 

### Dealing with textual changes

Manuscript text alterations should be carefully documented in the rebuttal letter and indicated in a copy of the manuscript according to the instructions provided by the journal.

### Writing the rebuttal letter

The response letter to the editor should be sent within the prescribed period and start with manuscript details (reference number, author, title), then a short and polite summary of how the reviewers concerns have been addressed and how this has made the manuscript stronger. The rebuttal should quote each reviewer point one by one, and under each of these put the author rebuttal or response to that point. This includes details of any text alterations, arguments and additional work done to address the point. 

If a point raised by reviewer 2 was dealt with in response to reviewer 1 simply indicate this and do not repeat the material. Where text was amended exactly as the reviewer requested, indicate this. Do not constantly thank the reviewers for ‘raising important points’, but equally do not be impolite or caustic. 

### Substantial alterations and extra work

If there is a demand for a lot of extra work to be done, it needs to be considered whether it is better to comply or to withdraw manuscript from review and submit elsewhere. This needs extensive consultation with the co-authors.

### Second stage reviews and later

Upon returning the manuscript after the first peer review (and rebuttal) the hope is that the editor and reviewers will scan the list of points raised (and responses given), note that all review points have been addressed then then wave it through with only minor quibbles. The tacit contract with the manuscript writer is that if all of the points raised in the first peer review are addressed then the manuscript should be accepted for publication. Points that were not raised in the first response should ideally not be raised later without good reason, especially if further author response to critique is not allowed.  

After second review the manuscript will again return to the authors, and with luck there will be a request from the editor for the manuscript undergo only minor revision (which may not involve the peer reviewers further) which makes it easy to reach acceptance with the final resubmission. It is not so common to get a rejection after second review but it certainly happens, notably with the very high impact factor journals. 

With final acceptance the burden is almost lifted but not quite, administrative matters remain, such as bill payments and checking of proofs. However, it is not an unreasonable point to celebrate.
